version: '3.9'

services:
  backd-dev:
    hostname: backd-dev
    tty: true
    privileged: true
    cap_add:
      - ALL
    working_dir: /root
    build:
      context: ./dev
      dockerfile: Dockerfile
    volumes:
      - ./daemon:/root/backd
    ports:
      - '0.0.0.0:7000:3000'
    expose:
      - 7000
